version: "3.9"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&             
             pip install debugpy -t /tmp &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
      - 5678:5678
    # restart em caso de crash
    restart: always
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - HOST_ADDRESS=${HOST_ADDRESS}


