# Generated by Django 4.1 on 2022-10-04 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SellerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicos.product', verbose_name='Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicos.seller', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Seller Inventory',
                'verbose_name_plural': 'Sellers Inventories',
                'ordering': ['seller', 'product'],
                'unique_together': {('seller', 'product')},
            },
        ),
    ]
